### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by simmarn** [maxifier/cliche-shell#9]
Ubuntu 14.04 and maven3.
eartino@elx6ltpyz1-mo ~/g/cliche-shell> git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
eartino@elx6ltpyz1-mo ~/g/cliche-shell> git describe
cliche-shell-1.1.13-2-g8cadf19
eartino@elx6ltpyz1-mo ~/g/cliche-shell> mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: sv_SE, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-52-generic", arch: "amd64", family: "unix"
eartino@elx6ltpyz1-mo ~/g/cliche-shell> mvn
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project com.maxifier.cliche-shell:cliche-shell:1.1.14-SNAPSHOT (/home/eartino/git/cliche-shell/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find com.maxifier:maxifier-project:pom:2.5 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
eartino@elx6ltpyz1-mo ~/g/cliche-shell>

**Comment by SimonVolman** [comment]
I has removed internal dependency -  can you update project and try once again?

**Comment by simmarn** [comment]
Thanks. It ran a bit longer, but I got a new error. I have not used maven before so I do not know if I miss some kind of setting.
----
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Cliche Shell ...................................... SUCCESS [17.792s]
[INFO] Cliche Shell::Core ................................ FAILURE [3.942s]
[INFO] Cliche Shell:Guice ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.834s
[INFO] Finished at: Tue May 19 08:37:57 CEST 2015
[INFO] Final Memory: 13M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cliche-shell-core: Could not resolve dependencies for project com.maxifier.cliche-shell:cliche-shell-core:jar:1.1.14-SNAPSHOT: Could not find artifact data-exporter:data-exporter:jar:1.0.2 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cliche-shell-core
eartino@elx6ltpyz1-mo ~/g/cliche-shell> 

----

**Comment by SimonVolman** [comment]
it is small library which we use for testing porpose mostly
which not available on your external maven repository (http://repo.maven.apache.org)

You have to attach additional external repository
or build artifact from sources: https://github.com/brsanthu/data-exporter/
and install it into your local repository
 mvn install:install-file -Dfile=<path-to-file>

**Comment by simmarn** [comment]
Great. Thanks. I was able to compile core. But not guice. 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Cliche Shell:Guice 1.1.14-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.maxifier.guice:guice:jar:3.0.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Cliche Shell ...................................... SUCCESS [0.842s]
[INFO] Cliche Shell::Core ................................ SUCCESS [4.152s]
[INFO] Cliche Shell:Guice ................................ FAILURE [0.010s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.104s
[INFO] Finished at: Tue May 19 10:45:33 CEST 2015
[INFO] Final Memory: 25M/316M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cliche-shell-guice: Could not resolve dependencies for project com.maxifier.cliche-shell:cliche-shell-guice:jar:1.1.14-SNAPSHOT: Failure to find com.maxifier.guice:guice:jar:3.0.1 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cliche-shell-guice

**Comment by SimonVolman** [comment]
Sorry for inconvenience - I has changed some internal dependancy

Can you update and try once again?

**Comment by simmarn** [comment]
It worked. Thanks!
